when:
  - event: push
    branch: main

steps:
  - name: deploy
    image: docker:27
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker compose build
      - docker compose up -d